### ISSUE TITLE
In node -1 (importClip): UNSUPPORTED_NODE: Assertion failed: inputs.at(2).is_weights() && "Clip max value must be an initializer!"

### ISSUE THREAD

**Issue by willianLee** [leandro-svg/SparseInst_TensorRT#1]
how to solve it

**Comment by leandro-svg** [comment]
Dear WillianLee,
I'm glad you could use this repository.

Would you share with me your terminal command and the error log such that i could see where in the ONNX graph the error happens? 

Also, I could find a useful link for this issue  : 
https://github.com/onnx/onnx-tensorrt/issues/562

It says that the clip layer must have a maximum value in the clip node.  You can set the max value up by modifying the ONNX graph directly. Btw, my personal ONNX graph does only have minimal value in the Clip  layer.
If you haven't heard about ONNX graph, I suggest you to install netron, a tool to check your onnx graph.
To modify it, you could use : https://github.com/NVIDIA/TensorRT/tree/master/tools/onnx-graphsurgeon
![clip_layer](https://user-images.githubusercontent.com/63758148/186362636-dfe19bce-7b58-4449-82ed-dfb6cda7b17b.png)

**Comment by willianLee** [comment]
thanks&nbsp; for your reply.&nbsp; the terminal command is&nbsp; 'python build_engine.py', parameters are all default. tensorrt log is in the attachment.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leandro-svg/SparseInst_TensorRT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月24日(星期三) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leandro-svg/SparseInst_TensorRT] In node -1 (importClip): UNSUPPORTED_NODE: Assertion failed: inputs.at(2).is_weights() &amp;&amp; "Clip max value must be an initializer!" (Issue #1)





 
Dear WillianLee,
 I'm glad you could use this repository.
 
Would you share with me your terminal command and the error log such that i could see where in the ONNX graph the error happens?
 
Also, I could find a useful link for this issue  :
 onnx/onnx-tensorrt#562
 
It says that the clip layer must have a maximum value in the clip node.  You can set the max value up by modifying the ONNX graph directly. Btw, my personal ONNX graph does only have minimal value in the Clip  layer.
 If you haven't heard about ONNX graph, I suggest you to install netron, a tool to check your onnx graph.

**Comment by leandro-svg** [comment]
Since i have never met this issue, it could be due to some different versions of TensorRT or ONNX. I am using ONNX version 1.9.0 and TensorRT version 8.0.1.6 on my jetson TX2.
Here is a link where which you can find different version of Clip node for different ONNX : https://github.com/onnx/onnx/blob/main/docs/Operators.md#Clip
. Anyway, try to set a maximum value for the Clip node woth GraphSurgeon (see Issue link above) and it should be solved.  I hope.

For Clip-6 :
Attributes
max : float (default is (3.402823e+38))
Maximum value, above which element is replaced by max
min : float (default is (-3.402823e+38))
Minimum value, under which element is replaced by min

**Comment by willianLee** [comment]
Much appreciated.&nbsp;I'll have a try as you said.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leandro-svg/SparseInst_TensorRT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月24日(星期三) 下午4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leandro-svg/SparseInst_TensorRT] In node -1 (importClip): UNSUPPORTED_NODE: Assertion failed: inputs.at(2).is_weights() &amp;&amp; "Clip max value must be an initializer!" (Issue #1)





 
Since i have never met this issue, it could be due to some different versions of TensorRT or ONNX.
 Here is a link where which you can find different version of Clip node for different ONNX : https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Clip-6
 . Anyway, try to set a maximum value for the Clip node woth GraphSurgeon (see Issue link above) and it should be solved.  I hope.
 
For Clip-6 :
 Attributes
 max : float (default is (3.402823e+38))
 Maximum value, above which element is replaced by max
 min : float (default is (-3.402823e+38))
 Minimum value, under which element is replaced by min

**Comment by leandro-svg** [comment]
I'll try this out on another GPU (Nvidia 2070 Max-Q) and i'll keep you up to date :)
Thank you again for reaching out and good luck.

**Comment by leandro-svg** [comment]
Interesting link to add a constant : 
https://github.com/NVIDIA/TensorRT/tree/main/tools/onnx-graphsurgeon/examples/05_folding_constants

**Comment by leandro-svg** [comment]
Someone got this Clip issue and could solve it by using a docker image with CUDA 11.7, Pytorch 1.13 and TensorRT 8.2.5.
See comment from @LiZheng1997:  https://github.com/hustvl/SparseInst/issues/75
