### ISSUE TITLE
ONNX Inferencing Error

### ISSUE THREAD

**Issue by mohamadmansourX** [leandro-svg/SparseInst_TensorRT#7]
Hello,
Thank you for this great project to properly convert SparseInst to Onnx/TensorRT.

I started training through your updated implementation using a customized version of `configs/sparse_inst_r50_giam_aug.yaml` and 10 classes

I converted to onnx successfully
```
python3 convert_onnx.py --config-file configs/sparse_inst_r50_giam_aug.yaml --output on2/myonnx2.onnx --image assets/figures/t1.jpg --opts MODEL.WEIGHTS output/checkpoints/model_0001999.pth
```

Then when trying to inference using  
```
python3 eval_tensorrt_onnx.py  -c 0.2 --width_resized 640 --height_resized 640 --input assets/figures/* --use_onnx --onnx_engine on2/myonnx2.onnx --output_onnx on2/ --save_image
```
I'm receiving the below error!

```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from on2/myonnx2.onnx failed:Type 
Error: Type parameter (T) of Optype (Add) bound to different types (tensor(float) and tensor(double) in node (Add_398).
```

**Comment by leandro-svg** [comment]
Dear @mohamadmansourX, thank you for saying that 😉
Would you mind sharing your ONNX file  with me? Such that I can check it out on netron with the verbose output. 

On my ONNX, the last Add node I have a the Add_319 which is link to the "rescoring_mask" definition in the sparseinst.py, called line 229. If it is the case, you should be able to change line 21 which define mask_pred_ as a float that could possibily be converted to double. 
Let's see from where your Add_398  comes from ...

**Comment by mohamadmansourX** [comment]
Hello, thank you for your reply.
Yeah as you mentioned, after debugging with netron, the issue is in this line:
https://github.com/leandro-svg/SparseInst_TensorRT/blob/1bbff3c2b69ccaaf8053220e4725ab0620a84fed/sparseinst/sparseinst.py#L22

Adding the terms `mask_pred_.sum([1, 2])` and `1e-6` is causing that issue.
Tried changing `1e-6` to `torch.tensor(1e-6).float()` but for some reason it's still being interpreted as a tensor(double)!

**Comment by mohamadmansourX** [comment]
Done!!
I solved it by converting the array to double then float rather than 1e-6. Not sure why 1e-6 was mapped to double no matter what I do.
My solution:
```python
@torch.jit.script
def rescoring_mask(scores, mask_pred, masks):
    mask_pred_ = mask_pred.float()
    factrr = mask_pred_.sum([1, 2]).double()
    factrr = factrr + 1e-6
    return scores * ((masks * mask_pred_).sum([1, 2]) / factrr.float())
```
